import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "next-themes";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar"

const jetbrainsMono = JetBrains_Mono({ subsets: ['latin'], variable: '--font-mono' });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-mono", jetbrainsMono.variable)}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">

        <ThemeProvider attribute="class" enableSystem defaultTheme="system">

          <Navbar></Navbar>


          {/* sideBar template */}

          <div className="flex">
            <div className="hidden md:block h-[100vh] w-[300px] bg-red-500">
              <Sidebar/>
            </div>

            <div className="p-5 w-full md:max-w-[1140px]">
              {children}
            </div>

          </div>


          {/* end sideBar template */}

        </ThemeProvider>

      </body>
    </html>
  );
}
